# Copyright Contributors to the Open Cluster Management project

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}          
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          golangci-lint --version
      - name: Build project
        run: |
          make buildtar
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          files: |
            bin/kubectr_darwin_amd64.tar.gz
            bin/kubectr_darwin_arm64.tar.gz
            bin/kubectr_linux_amd64.tar.gz
            bin/kubectr_linux_arm64.tar.gz
            bin/kubectr_windows_amd64.zip
          draft: false
          prerelease: false
#      - name: Update new version in krew-index
#        uses: rajatjindal/krew-release-bot@v0.0.39